import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import membersRouter from "./members";
import productsRouter from "./products";
import dashboardRouter from "./dashboard";
import tracksRouter from "./tracks";
import progressRouter from "./progress";
import coachingRouter from "./coaching";
import ticketsRouter from "./tickets";
import announcementsRouter from "./announcements";
import webhooksRouter from "./webhooks";
import webhooksGhlRouter from "./webhooks-ghl";
import devSimulateRouter from "./dev-simulate";
import adminWebhooksRouter from "./admin-webhooks";
import adminExpirationRouter from "./admin-expiration";
import onboardingRouter from "./onboarding";
import documentsRouter from "./documents";
import communityRouter from "./community";
import adminGhlRouter from "./admin-ghl";
import adminTicketsRouter from "./admin-tickets";
import chatRouter from "./chat";
import adminTracksRouter from "./admin-tracks";
import adminModulesRouter from "./admin-modules";
import adminLessonsRouter from "./admin-lessons";
import adminResourcesRouter from "./admin-resources";
import adminBulkRouter from "./admin-bulk";
import storageRouter from "./storage";
import communicationWebhooksRouter from "./communication-webhooks";
import emailRouter from "./email";
import memberCommunicationsRouter from "./member-communications";
import commissionsRouter from "./commissions";
import adminCommissionsRouter from "./admin-commissions";
import adminApiKeysRouter from "./admin-api-keys";
import v1HealthRouter from "./v1-health";

const router: IRouter = Router();

router.use(healthRouter);
router.use(v1HealthRouter);
router.use(authRouter);
router.use(membersRouter);
router.use(productsRouter);
router.use(dashboardRouter);
router.use(tracksRouter);
router.use(progressRouter);
router.use(coachingRouter);
router.use(ticketsRouter);
router.use(announcementsRouter);
router.use(webhooksRouter);
router.use(webhooksGhlRouter);
router.use(communicationWebhooksRouter);
router.use(emailRouter);
router.use(memberCommunicationsRouter);
router.use(devSimulateRouter);
router.use(adminWebhooksRouter);
router.use(adminExpirationRouter);
router.use(onboardingRouter);
router.use(documentsRouter);
router.use(communityRouter);
router.use(adminGhlRouter);
router.use(adminTicketsRouter);
router.use(chatRouter);
router.use(adminTracksRouter);
router.use(adminModulesRouter);
router.use(adminLessonsRouter);
router.use(adminResourcesRouter);
router.use(adminBulkRouter);
router.use(storageRouter);
router.use(commissionsRouter);
router.use(adminCommissionsRouter);
router.use(adminApiKeysRouter);

export default router;
