import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import membersRouter from "./members";
import productsRouter from "./products";
import dashboardRouter from "./dashboard";
import tracksRouter from "./tracks";
import progressRouter from "./progress";
import courseProgressRouter from "./course-progress";
import coachingRouter from "./coaching";
import ticketsRouter from "./tickets";
import announcementsRouter from "./announcements";
import webhooksRouter from "./webhooks";
import webhooksGhlRouter from "./webhooks-ghl";
import devSimulateRouter from "./dev-simulate";
import adminWebhooksRouter from "./admin-webhooks";
import adminExpirationRouter from "./admin-expiration";
import onboardingRouter from "./onboarding";
import documentsRouter from "./documents";
import communityRouter from "./community";
import adminGhlRouter from "./admin-ghl";
import adminTicketsRouter from "./admin-tickets";
import adminCommunityRouter from "./admin-community";
import chatRouter from "./chat";
import adminTracksRouter from "./admin-tracks";
import adminModulesRouter from "./admin-modules";
import adminLessonsRouter from "./admin-lessons";
import adminResourcesRouter from "./admin-resources";
import adminBulkRouter from "./admin-bulk";
import adminChatRouter from "./admin-chat";
import storageRouter from "./storage";
import communicationWebhooksRouter from "./communication-webhooks";
import emailRouter from "./email";
import memberCommunicationsRouter from "./member-communications";
import commissionsRouter from "./commissions";
import adminCommissionsRouter from "./admin-commissions";
import adminApiKeysRouter from "./admin-api-keys";
import adminRevenueRouter from "./admin-revenue";
import adminCommunicationsRouter from "./admin-communications";
import v1HealthRouter from "./v1-health";
import winsRouter from "./wins";
import adminWinsRouter from "./admin-wins";
import marketingRouter from "./marketing";
import toolsRouter from "./tools";
import adminOutgoingWebhooksRouter from "./admin-outgoing-webhooks";
import vaultRouter from "./vault";
import coachingOneOnOneRouter from "./coaching-one-on-one";
import adminCoachingRouter from "./admin-coaching";
import adminVaultRouter from "./admin-vault";
import adminToolsRouter from "./admin-tools";
import adminPanelRouter from "./admin-panel";
import aiChatRouter from "./openai/chat.js";
import kbPipelineRouter from "./admin/knowledgebase-pipeline.js";
import kbStagingRouter from "./admin/knowledgebase-staging.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(v1HealthRouter);
router.use(authRouter);
router.use(membersRouter);
router.use(productsRouter);
router.use(dashboardRouter);
router.use(tracksRouter);
router.use(progressRouter);
router.use(courseProgressRouter);
router.use(coachingRouter);
router.use(coachingOneOnOneRouter);
router.use(ticketsRouter);
router.use(announcementsRouter);
router.use(webhooksRouter);
router.use(webhooksGhlRouter);
router.use(communicationWebhooksRouter);
router.use(emailRouter);
router.use(memberCommunicationsRouter);
router.use(devSimulateRouter);
router.use(adminWebhooksRouter);
router.use(adminExpirationRouter);
router.use(onboardingRouter);
router.use(documentsRouter);
router.use(communityRouter);
router.use(adminGhlRouter);
router.use(adminTicketsRouter);
router.use(adminCommunityRouter);
router.use(chatRouter);
router.use(adminTracksRouter);
router.use(adminModulesRouter);
router.use(adminLessonsRouter);
router.use(adminResourcesRouter);
router.use(adminBulkRouter);
router.use(adminChatRouter);
router.use(storageRouter);
router.use(commissionsRouter);
router.use(adminCommissionsRouter);
router.use(adminApiKeysRouter);
router.use(adminRevenueRouter);
router.use(winsRouter);
router.use(adminWinsRouter);
router.use(marketingRouter);
router.use(toolsRouter);
router.use(adminOutgoingWebhooksRouter);
router.use(vaultRouter);
router.use(adminCoachingRouter);
router.use(adminVaultRouter);
router.use(adminCommunicationsRouter);
router.use(adminToolsRouter);
router.use(adminPanelRouter);
router.use("/ai-chat", aiChatRouter);
router.use("/admin/knowledgebase/pipeline", kbPipelineRouter);
router.use("/admin/knowledgebase/staging", kbStagingRouter);

export default router;
