import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import membersRouter from "./members";
import productsRouter from "./products";
import dashboardRouter from "./dashboard";
import tracksRouter from "./tracks";
import progressRouter from "./progress";
import courseProgressRouter from "./course-progress";
import blitzLessonsRouter from "./blitz-lessons";
import blitzProgressRouter from "./blitz-progress";
import coachingRouter from "./coaching";
import ticketsRouter from "./tickets";
import announcementsRouter from "./announcements";
import webhooksRouter from "./webhooks";
import webhooksGhlRouter from "./webhooks-ghl";
import devSimulateRouter from "./dev-simulate";
import adminWebhooksRouter from "./admin-webhooks";
import adminExpirationRouter from "./admin-expiration";
import onboardingRouter from "./onboarding";
import documentsRouter from "./documents";
import communityRouter from "./community";
import adminGhlRouter from "./admin-ghl";
import adminTicketsRouter from "./admin-tickets";
import adminCommunityRouter from "./admin-community";
import chatRouter from "./chat";
import adminTracksRouter from "./admin-tracks";
import adminModulesRouter from "./admin-modules";
import adminLessonsRouter from "./admin-lessons";
import adminResourcesRouter from "./admin-resources";
import adminBulkRouter from "./admin-bulk";
import adminChatRouter from "./admin-chat";
import storageRouter from "./storage";
import communicationWebhooksRouter from "./communication-webhooks";
import emailRouter from "./email";
import memberCommunicationsRouter from "./member-communications";
import commissionsRouter from "./commissions";
import adminCommissionsRouter from "./admin-commissions";
import adminApiKeysRouter from "./admin-api-keys";
import adminRevenueRouter from "./admin-revenue";
import adminRefundMetricsRouter from "./admin-refund-metrics";
import adminCommunicationsRouter from "./admin-communications";
import v1HealthRouter from "./v1-health";
import winsRouter from "./wins";
import adminWinsRouter from "./admin-wins";
import marketingRouter from "./marketing";
import toolsRouter from "./tools";
import adminOutgoingWebhooksRouter from "./admin-outgoing-webhooks";
import vaultRouter from "./vault";
import coachingSessionsRouter from "./coaching-sessions";
import adminCoachingSessionsRouter from "./admin-coaching-sessions";
import adminCoachingCallsRouter from "./admin-coaching-calls";
import adminCoachesRouter from "./admin-coaches";
import adminPartnersRouter from "./admin-partners";
import adminVaultRouter from "./admin-vault";
import adminToolsRouter from "./admin-tools";
import adminPanelRouter from "./admin-panel";
import aiChatRouter from "./openai/chat.js";
import kbPipelineRouter from "./admin/knowledgebase-pipeline.js";
import kbStagingRouter from "./admin/knowledgebase-staging.js";
import kbSourcesRouter from "./admin/knowledgebase-sources.js";
import kbArchiveRouter from "./admin/knowledgebase-archive.js";
import kbNavRouter from "./admin/knowledgebase-nav.js";
import kbToolTagsRouter from "./admin/kb-tool-tags.js";
import kbSynonymProposalsRouter from "./admin/kb-synonym-proposals.js";
import houseTermsRouter from "./admin/house-terms.js";
import aiLiveDocumentsRouter from "./admin/ai-live-documents.js";
import aiSourceDocumentsRouter from "./admin/ai-source-documents.js";
import kbValueScreenerRouter from "./admin/kb-value-screener.js";
import transcriptCleanerRouter from "./admin/transcript-cleaner.js";
import adminModerationQueueRouter from "./admin/moderation.js";
import adminWordlistRouter from "./admin/wordlist.js";
import adminStrikesRouter from "./admin/strikes.js";
import appsRouter from "./apps";
import adminAppsRouter from "./admin-apps";
import analyticsRouter from "./analytics";
import integrationsRouter from "./integrations";
import affiliateNetworksRouter from "./admin-affiliate-networks";
import mediaMavensProductsRouter from "./admin-media-mavens-products";
import mediaMavensCategoriesRouter from "./admin-media-mavens-categories";
import dmRouter from "./dm";
import adminAssistantGeneratorRouter from "./admin/assistant-generator.js";
import assistantCardsRouter from "./assistant-cards";
import adminAssistantCardsRouter from "./admin-assistant-cards";
import coachDashboardRouter from "./coach-dashboard";
import coachGoogleRouter from "./coach-google";
import mediaMavensLinksRouter from "./media-mavens-links";
import mediaMavensPerformanceRouter from "./media-mavens-performance";
import tapfiliateSSORrouter from "./tapfiliate-sso";
import voiceRouter from "./voice";
import webhooksRetellRouter from "./webhooks-retell";
import adminFulfillmentCatalogRouter from "./admin-fulfillment-catalog";
import kbSearchRouter from "./kb-search";
import contentAccessRouter from "./content-access";
import adminContentGapsRouter from "./admin-content-gaps";
import billingRouter from "./billing";
import adSpendRouter from "./ad-spend";
import opsRouter from "./ops";
import callBookingsRouter from "./call-bookings";
import partnerDashboardRouter from "./partner-dashboard";

const router: IRouter = Router();

router.use(healthRouter);
router.use(v1HealthRouter);
router.use(authRouter);
router.use(membersRouter);
router.use(productsRouter);
router.use(blitzLessonsRouter);
router.use(blitzProgressRouter);
router.use(dashboardRouter);
router.use(tracksRouter);
router.use(progressRouter);
router.use(courseProgressRouter);
router.use(coachingRouter);
router.use(coachingSessionsRouter);
router.use(ticketsRouter);
router.use(announcementsRouter);
router.use(webhooksRouter);
router.use(webhooksGhlRouter);
router.use(communicationWebhooksRouter);
router.use(emailRouter);
router.use(memberCommunicationsRouter);
router.use(devSimulateRouter);
router.use(adminWebhooksRouter);
router.use(adminExpirationRouter);
router.use(onboardingRouter);
router.use(documentsRouter);
router.use(communityRouter);
router.use(adminGhlRouter);
router.use(adminTicketsRouter);
router.use(adminCommunityRouter);
router.use(chatRouter);
router.use(adminTracksRouter);
router.use(adminModulesRouter);
router.use(adminLessonsRouter);
router.use(adminResourcesRouter);
router.use(adminBulkRouter);
router.use(adminChatRouter);
router.use(storageRouter);
router.use(commissionsRouter);
router.use(adminCommissionsRouter);
router.use(adminApiKeysRouter);
router.use(adminRevenueRouter);
router.use(adminRefundMetricsRouter);
router.use(winsRouter);
router.use(adminWinsRouter);
router.use(marketingRouter);
router.use(toolsRouter);
router.use(adminOutgoingWebhooksRouter);
router.use(vaultRouter);
router.use(adminCoachingSessionsRouter);
router.use(adminCoachingCallsRouter);
router.use(adminCoachesRouter);
router.use(adminPartnersRouter);
router.use(adminVaultRouter);
router.use(adminCommunicationsRouter);
router.use(adminToolsRouter);
router.use(adminPanelRouter);
router.use("/ai-chat", aiChatRouter);
router.use("/admin/knowledgebase/pipeline", kbPipelineRouter);
router.use("/admin/knowledgebase/staging", kbStagingRouter);
router.use("/admin/knowledgebase/sources", kbSourcesRouter);
router.use("/admin/knowledgebase/archive", kbArchiveRouter);
router.use("/admin/knowledgebase/nav", kbNavRouter);
router.use("/admin/knowledgebase/tool-tags", kbToolTagsRouter);
router.use("/admin/knowledgebase/synonym-proposals", kbSynonymProposalsRouter);
router.use("/admin/knowledgebase/house-terms", houseTermsRouter);
router.use(aiLiveDocumentsRouter);
router.use(aiSourceDocumentsRouter);
router.use(kbValueScreenerRouter);
router.use(transcriptCleanerRouter);
router.use("/admin/moderation/queue", adminModerationQueueRouter);
router.use("/admin/wordlist", adminWordlistRouter);
router.use("/admin/strikes", adminStrikesRouter);
router.use(appsRouter);
router.use(adminAppsRouter);
router.use(analyticsRouter);
router.use(integrationsRouter);
router.use(affiliateNetworksRouter);
router.use(mediaMavensProductsRouter);
router.use(mediaMavensCategoriesRouter);
router.use("/dm", dmRouter);
router.use(adminAssistantGeneratorRouter);
router.use(assistantCardsRouter);
router.use(adminAssistantCardsRouter);
router.use(coachDashboardRouter);
router.use(coachGoogleRouter);
router.use(mediaMavensLinksRouter);
router.use(mediaMavensPerformanceRouter);
router.use(tapfiliateSSORrouter);
router.use(voiceRouter);
router.use(webhooksRetellRouter);
router.use(adminFulfillmentCatalogRouter);
router.use(kbSearchRouter);
router.use(contentAccessRouter);
router.use(adminContentGapsRouter);
router.use(billingRouter);
router.use(adSpendRouter);
router.use(opsRouter);
router.use(callBookingsRouter);
router.use(partnerDashboardRouter);

export default router;
